"""
Generated ARC-56 AppClient and AVM AppClient bindings for the ASA Metadata Registry.

This subpackage is designed to be regenerated by `algokit-client-generator` and
`puyapy-clientgen` without affecting the rest of the SDK.
"""
