"""
Generated ARC-56 AppClient bindings for the ASA Metadata Registry.

This subpackage is designed to be regenerated by `algokit-client-generator` without
affecting the rest of the SDK.

The SDK imports this module lazily when needed.
"""
