from smart_contracts.asa_metadata_registry import flags

MASK_ID_SHORT = 1 << flags.FLG_ID_SHORT

MASK_ARC20 = 1 << flags.FLG_ARC20
MASK_ARC62 = 1 << flags.FLG_ARC62
MASK_RESERVED_2 = 1 << flags.FLG_RESERVED_2
MASK_RESERVED_3 = 1 << flags.FLG_RESERVED_3
MASK_ARC3 = 1 << flags.FLG_ARC3
MASK_ARC89_NATIVE = 1 << flags.FLG_ARC89_NATIVE
MASK_RESERVED_6 = 1 << flags.FLG_RESERVED_6
MASK_IMMUTABLE = 1 << flags.FLG_IMMUTABLE

MASK_REVERSIBLE = MASK_ARC20 | MASK_ARC62 | MASK_RESERVED_2 | MASK_RESERVED_3
MASK_IRREV_CREATION_ONLY = MASK_ARC3 | MASK_ARC89_NATIVE
MASK_IRREV_ANYTIME = MASK_RESERVED_6 | MASK_IMMUTABLE
